/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bushido_dojo.Editar;

import bd.conexaoBD.BDSQLServer;
import bd.conexaoBD.core.MeuResultSet;
import com.mycompany.bushido_dojo.jframeHome;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dudac
 */
public class jframeHorarios extends javax.swing.JFrame {

    /**
     * Creates new form jframeHorarios
     */
    public jframeHorarios() {
        initComponents();
        fillComboBoxHorario();
        fillComboBoxProfessor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelBushido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        curvedGradientePanel1 = new procedimentos.CurvedGradientePanel();
        jLabel2 = new javax.swing.JLabel();
        jFieldHorarioInicio = new javax.swing.JTextField();
        labelIdHorario = new javax.swing.JLabel();
        labelHorarios3 = new javax.swing.JLabel();
        jcomboTurma = new javax.swing.JComboBox<>();
        labelHorarios4 = new javax.swing.JLabel();
        jcomboHorario = new javax.swing.JComboBox<>();
        labelHorarios5 = new javax.swing.JLabel();
        jcomboDiaSemana = new javax.swing.JComboBox<>();
        labelHorarios6 = new javax.swing.JLabel();
        labelHorarios7 = new javax.swing.JLabel();
        labelHorarios8 = new javax.swing.JLabel();
        jcomboProfessor = new javax.swing.JComboBox<>();
        buttonAtualizar = new procedimentos.RoundButton();
        buttonAdicionar = new procedimentos.RoundButton();
        jbotaoSairHome = new javax.swing.JButton();
        labelNome2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(13, 32, 51));
        jPanel1.setLayout(null);

        jLabelBushido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N
        jPanel1.add(jLabelBushido);
        jLabelBushido.setBounds(10, 0, 50, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BushidoDojo DomineODomDaArte.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 10, 310, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 80);

        curvedGradientePanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Atletico Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Horarios");
        curvedGradientePanel1.add(jLabel2);
        jLabel2.setBounds(220, 20, 110, 30);
        curvedGradientePanel1.add(jFieldHorarioInicio);
        jFieldHorarioInicio.setBounds(320, 200, 150, 22);

        labelIdHorario.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelIdHorario.setForeground(new java.awt.Color(255, 255, 255));
        curvedGradientePanel1.add(labelIdHorario);
        labelIdHorario.setBounds(250, 80, 50, 24);

        labelHorarios3.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelHorarios3.setForeground(new java.awt.Color(255, 255, 255));
        labelHorarios3.setText("Turma");
        curvedGradientePanel1.add(labelHorarios3);
        labelHorarios3.setBounds(160, 310, 70, 24);

        jcomboTurma.setBackground(new java.awt.Color(13, 32, 51));
        jcomboTurma.setForeground(new java.awt.Color(255, 255, 255));
        jcomboTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Turma", "A", "B" }));
        curvedGradientePanel1.add(jcomboTurma);
        jcomboTurma.setBounds(320, 310, 140, 22);

        labelHorarios4.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelHorarios4.setForeground(new java.awt.Color(255, 255, 255));
        labelHorarios4.setText("Horario Inicio");
        curvedGradientePanel1.add(labelHorarios4);
        labelHorarios4.setBounds(160, 200, 130, 24);

        jcomboHorario.setBackground(new java.awt.Color(13, 32, 51));
        jcomboHorario.setForeground(new java.awt.Color(255, 255, 255));
        jcomboHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Horario" }));
        jcomboHorario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcomboHorarioItemStateChanged(evt);
            }
        });
        curvedGradientePanel1.add(jcomboHorario);
        jcomboHorario.setBounds(570, 70, 150, 22);

        labelHorarios5.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelHorarios5.setForeground(new java.awt.Color(255, 255, 255));
        labelHorarios5.setText("Dia da Semana");
        curvedGradientePanel1.add(labelHorarios5);
        labelHorarios5.setBounds(160, 260, 140, 24);

        jcomboDiaSemana.setBackground(new java.awt.Color(13, 32, 51));
        jcomboDiaSemana.setForeground(new java.awt.Color(255, 255, 255));
        jcomboDiaSemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Dia da Semana", "Segunda-Feira", "Terça-Feira", "Quarta-Feira", "Quinta-Feira", "Sexta-Feira" }));
        curvedGradientePanel1.add(jcomboDiaSemana);
        jcomboDiaSemana.setBounds(320, 260, 180, 22);

        labelHorarios6.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelHorarios6.setForeground(new java.awt.Color(255, 255, 255));
        labelHorarios6.setText("Professor");
        curvedGradientePanel1.add(labelHorarios6);
        labelHorarios6.setBounds(170, 140, 90, 24);

        labelHorarios7.setFont(new java.awt.Font("Atletico Bold", 1, 14)); // NOI18N
        labelHorarios7.setForeground(new java.awt.Color(255, 255, 255));
        labelHorarios7.setText("Caso queira editar um horario selecione ele:");
        curvedGradientePanel1.add(labelHorarios7);
        labelHorarios7.setBounds(470, 30, 320, 18);

        labelHorarios8.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelHorarios8.setForeground(new java.awt.Color(255, 255, 255));
        labelHorarios8.setText("Id:");
        curvedGradientePanel1.add(labelHorarios8);
        labelHorarios8.setBounds(220, 80, 40, 24);

        jcomboProfessor.setBackground(new java.awt.Color(13, 32, 51));
        jcomboProfessor.setForeground(new java.awt.Color(255, 255, 255));
        jcomboProfessor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Professor" }));
        curvedGradientePanel1.add(jcomboProfessor);
        jcomboProfessor.setBounds(320, 140, 150, 22);

        buttonAtualizar.setText("Atualizar");
        buttonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtualizarActionPerformed(evt);
            }
        });
        curvedGradientePanel1.add(buttonAtualizar);
        buttonAtualizar.setBounds(370, 410, 100, 40);

        buttonAdicionar.setText("Adicionar");
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });
        curvedGradientePanel1.add(buttonAdicionar);
        buttonAdicionar.setBounds(230, 410, 100, 40);

        jbotaoSairHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/home.png"))); // NOI18N
        jbotaoSairHome.setBorderPainted(false);
        jbotaoSairHome.setContentAreaFilled(false);
        jbotaoSairHome.setFocusPainted(false);
        jbotaoSairHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotaoSairHomeActionPerformed(evt);
            }
        });
        curvedGradientePanel1.add(jbotaoSairHome);
        jbotaoSairHome.setBounds(700, 400, 80, 80);

        labelNome2.setFont(new java.awt.Font("The Bold Font", 1, 14)); // NOI18N
        labelNome2.setText("Home");
        curvedGradientePanel1.add(labelNome2);
        labelNome2.setBounds(720, 460, 90, 20);

        getContentPane().add(curvedGradientePanel1);
        curvedGradientePanel1.setBounds(0, 80, 800, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcomboHorarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcomboHorarioItemStateChanged
        try {
            displaySelectedHorario();
        } catch (SQLException ex) {
            Logger.getLogger(jframeHorarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcomboHorarioItemStateChanged

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
    try {
        String idHorario = labelIdHorario.getText();
        
        if (idHorario.isEmpty()) {
            String horarioInicioString = jFieldHorarioInicio.getText();
            horarioInicioString = horarioInicioString + ":00";
            java.sql.Time horarioInicioSQL = java.sql.Time.valueOf(horarioInicioString);
            String turma = (String) jcomboTurma.getSelectedItem();
            String diaSemana = (String) jcomboDiaSemana.getSelectedItem();
            String nomeProfessor = (String) jcomboProfessor.getSelectedItem();
            
            int idProf = -1;
            String[] partes = nomeProfessor.split("\\s+"); 
            if (partes.length >= 2) {
                 idProf = Integer.parseInt(partes[0]);
            } else {
                System.out.println("Formato inválido do item selecionado.");
            }
            
            String query = "INSERT INTO Karate.HorariosAula (Id_Prof, HorarioInicio,diaSemana,Turma) values(?,?,?,?)";
            
            BDSQLServer.COMANDO.prepareStatement(query);
            BDSQLServer.COMANDO.setInt(1,idProf);
            BDSQLServer.COMANDO.setTime(2,horarioInicioSQL);
            BDSQLServer.COMANDO.setString(3,diaSemana);
            BDSQLServer.COMANDO.setString(4,turma);
            BDSQLServer.COMANDO.execute();
            BDSQLServer.COMANDO.commit();
            JOptionPane.showMessageDialog(this, "Novo registro inserido com sucesso.");
            new jframeHorarios().setVisible(true);
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(this, "Preencha os campos e pressione Atualizar para modificar.");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao adicionar registro: " + e.getMessage());
    }
    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void buttonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtualizarActionPerformed
        try{
            int idHorario = Integer.parseInt(labelIdHorario.getText());

            
            if(idHorario!=0){
                String horarioInicioString = jFieldHorarioInicio.getText();
                horarioInicioString = horarioInicioString + ":00";
                java.sql.Time horarioInicioSQL = java.sql.Time.valueOf(horarioInicioString);
                String turma = (String) jcomboTurma.getSelectedItem();
                String diaSemana = (String) jcomboDiaSemana.getSelectedItem();
                String nomeProfessor = (String) jcomboProfessor.getSelectedItem();

                int idProf = -1;
                String[] partes = nomeProfessor.split("\\s+"); 
                if (partes.length >= 2) {
                     idProf = Integer.parseInt(partes[0]);
                } else {
                    System.out.println("Formato inválido do item selecionado.");
                }
                
                String query = "UPDATE Karate.HorariosAula SET HorarioInicio = ?, DiaSemana = ?, Turma = ?, Id_Prof = ? WHERE Id_Horario = ?";
                
                BDSQLServer.COMANDO.prepareStatement(query);
                BDSQLServer.COMANDO.setTime(1,horarioInicioSQL);
                BDSQLServer.COMANDO.setString(2,diaSemana);
                BDSQLServer.COMANDO.setString(3,turma);
                BDSQLServer.COMANDO.setInt(4,idProf);
                BDSQLServer.COMANDO.setInt(5, idHorario);
                int linhasAtt = BDSQLServer.COMANDO.executeUpdate();
                
                if(linhasAtt>0){
                    JOptionPane.showMessageDialog(this, "Registro atualizado com sucesso!");
                    new jframeHorarios().setVisible(true);
                    this.dispose();
                }        
                else{
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar o registro" );
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Selecione um registro para atualizar.");
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(jframeHorarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonAtualizarActionPerformed

    private void jbotaoSairHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotaoSairHomeActionPerformed
        new jframeHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbotaoSairHomeActionPerformed
    private void fillComboBoxHorario() {
                try {
                    String query = "select Id_Horario from Karate.HorariosAula";

                    MeuResultSet resultado = (MeuResultSet)BDSQLServer.COMANDO.executeQuery (query);
                    
                    while (resultado.next()) {
                        jcomboHorario.addItem(resultado.getString(1));
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Erro ao preencher o ComboBox.");
                }

            }
    
    private void fillComboBoxProfessor(){
        try {
                    String query = """
                                   SELECT CONCAT(id_prof, ' ', nome) AS id_prof_nome
                                   FROM Karate.Professor;""";

                    MeuResultSet resultado = (MeuResultSet)BDSQLServer.COMANDO.executeQuery (query);
                    
                    while (resultado.next()) {
                        jcomboProfessor.addItem(resultado.getString(1));
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Erro ao preencher o ComboBox.");
                }
        
    }
    private void displaySelectedHorario() throws SQLException{
        try{
            String idHorario = (String) jcomboHorario.getSelectedItem();
            String query = """
                    SELECT Id_Horario, CONCAT(Professor.Id_Prof, ' ', Nome) AS Professor_Info, CAST(HorarioInicio AS CHAR(5)) AS Horario, DiaSemana, Turma
                    FROM Karate.HorariosAula
                    INNER JOIN Karate.Professor ON HorariosAula.Id_Prof = Professor.Id_Prof
                    WHERE Id_Horario = ?""";
            BDSQLServer.COMANDO.prepareStatement(query);
            BDSQLServer.COMANDO.setString(1,idHorario);
            MeuResultSet resultado = (MeuResultSet) BDSQLServer.COMANDO.executeQuery();
            
            if(resultado.next()){
                jFieldHorarioInicio.setText(resultado.getString(3));
                labelIdHorario.setText(idHorario);
                
                String turma = resultado.getString(5);
                String diaSemana = resultado.getString(4);
                String nomeProfessor = resultado.getString(2);
                
                jcomboProfessor.setSelectedItem(nomeProfessor);
                
                switch(diaSemana){
                    case "Segunda-Feira" -> jcomboDiaSemana.setSelectedItem("Segunda-Feira");
                    case "Terça-Feira" -> jcomboDiaSemana.setSelectedItem("Terça-Feira");
                    case "Quarta-Feira" -> jcomboDiaSemana.setSelectedItem("Quarta-Feira");
                    case "Quinta-Feira" -> jcomboDiaSemana.setSelectedItem("Quinta-Feira");
                    case "Sexta-Feira" -> jcomboDiaSemana.setSelectedItem("Sexta-Feira");
                    default -> jcomboDiaSemana.setSelectedIndex(0);
                }
                if(turma.equals("A")){
                    jcomboTurma.setSelectedItem("A");
                }
                else{
                    jcomboTurma.setSelectedItem("B");
                }
                
                
                
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Erro ao buscar informações do horário.");
            
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframeHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframeHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframeHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframeHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframeHorarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private procedimentos.RoundButton buttonAdicionar;
    private procedimentos.RoundButton buttonAtualizar;
    private procedimentos.CurvedGradientePanel curvedGradientePanel1;
    private javax.swing.JTextField jFieldHorarioInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBushido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbotaoSairHome;
    private javax.swing.JComboBox<String> jcomboDiaSemana;
    private javax.swing.JComboBox<String> jcomboHorario;
    private javax.swing.JComboBox<String> jcomboProfessor;
    private javax.swing.JComboBox<String> jcomboTurma;
    private javax.swing.JLabel labelHorarios3;
    private javax.swing.JLabel labelHorarios4;
    private javax.swing.JLabel labelHorarios5;
    private javax.swing.JLabel labelHorarios6;
    private javax.swing.JLabel labelHorarios7;
    private javax.swing.JLabel labelHorarios8;
    private javax.swing.JLabel labelIdHorario;
    private javax.swing.JLabel labelNome2;
    // End of variables declaration//GEN-END:variables
}
