/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bushido_dojo.Cadastros;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.*;
import procedimentos.*;
import bd.conexaoBD.BDSQLServer;
import com.mycompany.bushido_dojo.jframeHome;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dudac
 */
public class jframeCadastroAlunos extends javax.swing.JFrame {

    /**
     * Creates new form jframeCadastroAlunos
     */
    public jframeCadastroAlunos() {
        initComponents();
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        birthdayEvaluator1 = new com.toedter.calendar.demo.BirthdayEvaluator();
        jPanel1 = new javax.swing.JPanel();
        jpanel_Borda_Arredondada1 = new procedimentos.jpanel_Borda_Arredondada();
        jFieldCpf = new javax.swing.JFormattedTextField();
        jFieldNome = new javax.swing.JFormattedTextField();
        jFieldSobrenome = new javax.swing.JFormattedTextField();
        labelCpf1 = new javax.swing.JLabel();
        jComboBoxFaixas = new javax.swing.JComboBox<>();
        jFieldEmail = new javax.swing.JTextField();
        jFieldCelular = new javax.swing.JFormattedTextField();
        jDataNascimento = new com.toedter.calendar.JDateChooser();
        labelCpf2 = new javax.swing.JLabel();
        labelCpf3 = new javax.swing.JLabel();
        labelCpf4 = new javax.swing.JLabel();
        labelCpf5 = new javax.swing.JLabel();
        labelCpf6 = new javax.swing.JLabel();
        jpanel_Borda_Arredondada2 = new procedimentos.jpanel_Borda_Arredondada();
        jbotaoSairHome = new javax.swing.JButton();
        botaoCadastro = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        labelNome2 = new javax.swing.JLabel();
        labelNome1 = new javax.swing.JLabel();
        jpanel_Borda_Arredondada3 = new procedimentos.jpanel_Borda_Arredondada();
        labelAlunos = new javax.swing.JLabel();
        labelCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(13, 32, 51));
        jPanel1.setLayout(null);

        jpanel_Borda_Arredondada1.setBackground(new java.awt.Color(204, 204, 255));
        jpanel_Borda_Arredondada1.setLayout(null);

        try {
            jFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jpanel_Borda_Arredondada1.add(jFieldCpf);
        jFieldCpf.setBounds(90, 100, 90, 22);

        jFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFieldNomeKeyTyped(evt);
            }
        });
        jpanel_Borda_Arredondada1.add(jFieldNome);
        jFieldNome.setBounds(120, 9, 100, 22);

        jFieldSobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFieldSobrenomeKeyTyped(evt);
            }
        });
        jpanel_Borda_Arredondada1.add(jFieldSobrenome);
        jFieldSobrenome.setBounds(390, 9, 100, 22);

        labelCpf1.setFont(new java.awt.Font("The Bold Font", 1, 14)); // NOI18N
        labelCpf1.setForeground(new java.awt.Color(13, 32, 51));
        labelCpf1.setText("Faixa");
        jpanel_Borda_Arredondada1.add(labelCpf1);
        labelCpf1.setBounds(40, 190, 50, 15);

        jComboBoxFaixas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Faixa", "Branca", "Amarela", "Laranja", "Verde", "Azul", "Roxa", "Marrom", "Preta" }));
        jComboBoxFaixas.setName(""); // NOI18N
        jpanel_Borda_Arredondada1.add(jComboBoxFaixas);
        jComboBoxFaixas.setBounds(120, 180, 130, 22);

        jFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFieldEmailKeyTyped(evt);
            }
        });
        jpanel_Borda_Arredondada1.add(jFieldEmail);
        jFieldEmail.setBounds(400, 90, 100, 22);

        try {
            jFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jpanel_Borda_Arredondada1.add(jFieldCelular);
        jFieldCelular.setBounds(430, 180, 126, 22);
        jpanel_Borda_Arredondada1.add(jDataNascimento);
        jDataNascimento.setBounds(180, 290, 176, 22);

        labelCpf2.setFont(new java.awt.Font("The Bold Font", 1, 14)); // NOI18N
        labelCpf2.setForeground(new java.awt.Color(13, 32, 51));
        labelCpf2.setText("CPF");
        jpanel_Borda_Arredondada1.add(labelCpf2);
        labelCpf2.setBounds(40, 95, 40, 40);

        labelCpf3.setFont(new java.awt.Font("The Bold Font", 1, 14)); // NOI18N
        labelCpf3.setForeground(new java.awt.Color(13, 32, 51));
        labelCpf3.setText("sOBRENOME");
        jpanel_Borda_Arredondada1.add(labelCpf3);
        labelCpf3.setBounds(289, 14, 90, 15);

        labelCpf4.setFont(new java.awt.Font("The Bold Font", 1, 14)); // NOI18N
        labelCpf4.setForeground(new java.awt.Color(13, 32, 51));
        labelCpf4.setText("Email");
        jpanel_Borda_Arredondada1.add(labelCpf4);
        labelCpf4.setBounds(340, 85, 50, 30);

        labelCpf5.setFont(new java.awt.Font("The Bold Font", 1, 14)); // NOI18N
        labelCpf5.setForeground(new java.awt.Color(13, 32, 51));
        labelCpf5.setText("Celular");
        jpanel_Borda_Arredondada1.add(labelCpf5);
        labelCpf5.setBounds(320, 180, 70, 15);

        labelCpf6.setFont(new java.awt.Font("The Bold Font", 1, 18)); // NOI18N
        labelCpf6.setForeground(new java.awt.Color(13, 32, 51));
        labelCpf6.setText("DATA DE NASCIMENTO");
        jpanel_Borda_Arredondada1.add(labelCpf6);
        labelCpf6.setBounds(170, 260, 190, 19);

        jpanel_Borda_Arredondada2.setBackground(new java.awt.Color(251, 136, 52));
        jpanel_Borda_Arredondada2.setLayout(null);

        jbotaoSairHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/home.png"))); // NOI18N
        jbotaoSairHome.setBorderPainted(false);
        jbotaoSairHome.setContentAreaFilled(false);
        jbotaoSairHome.setFocusPainted(false);
        jbotaoSairHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotaoSairHomeActionPerformed(evt);
            }
        });
        jpanel_Borda_Arredondada2.add(jbotaoSairHome);
        jbotaoSairHome.setBounds(460, 0, 70, 70);

        botaoCadastro.setBackground(new java.awt.Color(251, 136, 52));
        botaoCadastro.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastroPNG.png"))); // NOI18N
        botaoCadastro.setBorder(new javax.swing.border.MatteBorder(null));
        botaoCadastro.setBorderPainted(false);
        botaoCadastro.setContentAreaFilled(false);
        botaoCadastro.setFocusPainted(false);
        botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroActionPerformed(evt);
            }
        });
        jpanel_Borda_Arredondada2.add(botaoCadastro);
        botaoCadastro.setBounds(10, 0, 60, 60);

        labelNome.setFont(new java.awt.Font("The Bold Font", 1, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(13, 32, 51));
        labelNome.setText("CADASTRAR");
        jpanel_Borda_Arredondada2.add(labelNome);
        labelNome.setBounds(10, 60, 80, 15);

        labelNome2.setFont(new java.awt.Font("The Bold Font", 1, 14)); // NOI18N
        labelNome2.setForeground(new java.awt.Color(13, 32, 51));
        labelNome2.setText("Home");
        jpanel_Borda_Arredondada2.add(labelNome2);
        labelNome2.setBounds(470, 60, 50, 15);

        jpanel_Borda_Arredondada1.add(jpanel_Borda_Arredondada2);
        jpanel_Borda_Arredondada2.setBounds(30, 380, 540, 80);

        labelNome1.setFont(new java.awt.Font("The Bold Font", 1, 14)); // NOI18N
        labelNome1.setForeground(new java.awt.Color(13, 32, 51));
        labelNome1.setText("Nome");
        jpanel_Borda_Arredondada1.add(labelNome1);
        labelNome1.setBounds(50, 14, 60, 15);

        jPanel1.add(jpanel_Borda_Arredondada1);
        jpanel_Borda_Arredondada1.setBounds(90, 70, 590, 480);

        jpanel_Borda_Arredondada3.setBackground(new java.awt.Color(100, 100, 100));
        jpanel_Borda_Arredondada3.setLayout(null);

        labelAlunos.setFont(new java.awt.Font("Atletico Bold", 1, 24)); // NOI18N
        labelAlunos.setForeground(new java.awt.Color(251, 136, 52));
        labelAlunos.setText("Alunos");
        jpanel_Borda_Arredondada3.add(labelAlunos);
        labelAlunos.setBounds(474, 6, 130, 50);

        labelCadastro.setFont(new java.awt.Font("Atletico Bold", 1, 24)); // NOI18N
        labelCadastro.setForeground(new java.awt.Color(255, 255, 255));
        labelCadastro.setText("Cadastro:");
        jpanel_Borda_Arredondada3.add(labelCadastro);
        labelCadastro.setBounds(6, 6, 130, 50);

        jPanel1.add(jpanel_Borda_Arredondada3);
        jpanel_Borda_Arredondada3.setBounds(80, 10, 610, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFieldNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFieldNomeKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c)||(c==KeyEvent.VK_SPACE) ||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_PERIOD)||(c==KeyEvent.VK_BACK_SPACE))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFieldNomeKeyTyped

    private void jFieldSobrenomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFieldSobrenomeKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c)||(c==KeyEvent.VK_SPACE) ||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_PERIOD)||(c==KeyEvent.VK_BACK_SPACE))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFieldSobrenomeKeyTyped

    private void jFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFieldEmailKeyTyped
        char c = evt.getKeyChar();
        if (Character.isWhitespace(c)) { // Verifica se o caractere é um espaço em branco
            evt.consume();
        }
    }//GEN-LAST:event_jFieldEmailKeyTyped

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroActionPerformed
        String nome = jFieldNome.getText();
        String cpf = jFieldCpf.getText();
        String sobrenome = jFieldSobrenome.getText();
        String email = jFieldEmail.getText();
        String celular = jFieldCelular.getText();
        Date dataNascimento = jDataNascimento.getDate();
        int idFaixa = -1;
        
        String corSelecionada = jComboBoxFaixas.getSelectedItem().toString();
        if(corSelecionada.equals("Selecione a Faixa")){
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma faixa válida.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        switch (corSelecionada) {
            case "Branca" -> idFaixa = 0;
            case "Amarela" -> idFaixa=1;
            case "Laranja" -> idFaixa=2;
            case "Verde" -> idFaixa=3;
            case "Azul" -> idFaixa=4;
            case "Roxa" -> idFaixa=5;
            case "Marrom" -> idFaixa=6;
            case "Preta" -> idFaixa=7;
            default -> {}
        }
        
        if(nome.isEmpty()||cpf.isEmpty()||sobrenome.isEmpty()||email.isEmpty()||celular.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Certifique-se de Completar todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String query = "EXEC Karate.spInsereAluno ?,  ?,  ?,  ?,  ?,  ?,  ?";
            
            try {
                BDSQLServer.COMANDO.prepareStatement(query);
                BDSQLServer.COMANDO.setInt(1,idFaixa);                
                BDSQLServer.COMANDO.setString(2,nome);                
                BDSQLServer.COMANDO.setString(3,sobrenome);
                BDSQLServer.COMANDO.setString(4,cpf);
                BDSQLServer.COMANDO.setString(5,email);
                BDSQLServer.COMANDO.setString(6,celular);
                
                if (dataNascimento != null) 
                {
                    java.sql.Date sqldataNascimento = new java.sql.Date(dataNascimento.getTime());
                    BDSQLServer.COMANDO.setDate(7,sqldataNascimento);   
                    BDSQLServer.COMANDO.execute();
                    BDSQLServer.COMANDO.commit();
                    JOptionPane.showMessageDialog(this, "Aluno Cadastrado..", "Alerta", JOptionPane.WARNING_MESSAGE);
                    new jframeCadastroAlunos().setVisible(true);
                    this.dispose();
                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "Por favor, selecione uma Data de Nascimento válida.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(jframeCadastroAlunos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
  
        
    }//GEN-LAST:event_botaoCadastroActionPerformed

    private void jbotaoSairHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotaoSairHomeActionPerformed
        new jframeHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbotaoSairHomeActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframeCadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframeCadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframeCadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframeCadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframeCadastroAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.demo.BirthdayEvaluator birthdayEvaluator1;
    private javax.swing.JButton botaoCadastro;
    private javax.swing.JComboBox<String> jComboBoxFaixas;
    private com.toedter.calendar.JDateChooser jDataNascimento;
    private javax.swing.JFormattedTextField jFieldCelular;
    private javax.swing.JFormattedTextField jFieldCpf;
    private javax.swing.JTextField jFieldEmail;
    private javax.swing.JFormattedTextField jFieldNome;
    private javax.swing.JFormattedTextField jFieldSobrenome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbotaoSairHome;
    private procedimentos.jpanel_Borda_Arredondada jpanel_Borda_Arredondada1;
    private procedimentos.jpanel_Borda_Arredondada jpanel_Borda_Arredondada2;
    private procedimentos.jpanel_Borda_Arredondada jpanel_Borda_Arredondada3;
    private javax.swing.JLabel labelAlunos;
    private javax.swing.JLabel labelCadastro;
    private javax.swing.JLabel labelCpf1;
    private javax.swing.JLabel labelCpf2;
    private javax.swing.JLabel labelCpf3;
    private javax.swing.JLabel labelCpf4;
    private javax.swing.JLabel labelCpf5;
    private javax.swing.JLabel labelCpf6;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNome1;
    private javax.swing.JLabel labelNome2;
    // End of variables declaration//GEN-END:variables
}
