/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bushido_dojo.Cadastros;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.*;
import procedimentos.*;
import bd.conexaoBD.BDSQLServer;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dudac
 */
public class jframeCadastroAlunos extends javax.swing.JFrame {

    /**
     * Creates new form jframeCadastroAlunos
     */
    public jframeCadastroAlunos() {
        initComponents();
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        birthdayEvaluator1 = new com.toedter.calendar.demo.BirthdayEvaluator();
        jPanel1 = new javax.swing.JPanel();
        jpanel_Borda_Arredondada1 = new procedimentos.jpanel_Borda_Arredondada();
        labelNome = new javax.swing.JLabel();
        jFieldCpf = new javax.swing.JFormattedTextField();
        jFieldNome = new javax.swing.JFormattedTextField();
        labelCelular = new javax.swing.JLabel();
        labelNome3 = new javax.swing.JLabel();
        jFieldSobrenome = new javax.swing.JFormattedTextField();
        labelCpf1 = new javax.swing.JLabel();
        jComboBoxFaixas = new javax.swing.JComboBox<>();
        labelFaixa = new javax.swing.JLabel();
        jFieldEmail = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        jFieldCelular = new javax.swing.JFormattedTextField();
        labelCelular1 = new javax.swing.JLabel();
        jDataNascimento = new com.toedter.calendar.JDateChooser();
        jpanel_Borda_Arredondada3 = new procedimentos.jpanel_Borda_Arredondada();
        labelAlunos = new javax.swing.JLabel();
        labelCadastro = new javax.swing.JLabel();
        botaoCadastro = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(13, 32, 51));
        jPanel1.setLayout(null);

        labelNome.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelNome.setForeground(new java.awt.Color(13, 32, 51));
        labelNome.setText("Nome");

        try {
            jFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFieldNomeKeyTyped(evt);
            }
        });

        labelCelular.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelCelular.setForeground(new java.awt.Color(13, 32, 51));
        labelCelular.setText("Data de Nascimento");

        labelNome3.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelNome3.setForeground(new java.awt.Color(13, 32, 51));
        labelNome3.setText("Sobrenome");

        jFieldSobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFieldSobrenomeKeyTyped(evt);
            }
        });

        labelCpf1.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelCpf1.setForeground(new java.awt.Color(13, 32, 51));
        labelCpf1.setText("CPF");

        jComboBoxFaixas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Faixa", "Branca", "Amarela", "Laranja", "Verde", "Azul", "Roxa", "Marrom", "Preta" }));
        jComboBoxFaixas.setName(""); // NOI18N

        labelFaixa.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelFaixa.setForeground(new java.awt.Color(13, 32, 51));
        labelFaixa.setText("Faixa");

        jFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFieldEmailKeyTyped(evt);
            }
        });

        labelEmail.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(13, 32, 51));
        labelEmail.setText("Email");

        try {
            jFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelCelular1.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelCelular1.setForeground(new java.awt.Color(13, 32, 51));
        labelCelular1.setText("Celular");

        javax.swing.GroupLayout jpanel_Borda_Arredondada1Layout = new javax.swing.GroupLayout(jpanel_Borda_Arredondada1);
        jpanel_Borda_Arredondada1.setLayout(jpanel_Borda_Arredondada1Layout);
        jpanel_Borda_Arredondada1Layout.setHorizontalGroup(
            jpanel_Borda_Arredondada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_Borda_Arredondada1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jpanel_Borda_Arredondada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_Borda_Arredondada1Layout.createSequentialGroup()
                        .addGroup(jpanel_Borda_Arredondada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jpanel_Borda_Arredondada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpanel_Borda_Arredondada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_Borda_Arredondada1Layout.createSequentialGroup()
                                .addComponent(labelNome3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_Borda_Arredondada1Layout.createSequentialGroup()
                                .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))
                    .addGroup(jpanel_Borda_Arredondada1Layout.createSequentialGroup()
                        .addComponent(labelFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jComboBoxFaixas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelCelular1)
                        .addGap(18, 18, 18))
                    .addGroup(jpanel_Borda_Arredondada1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jpanel_Borda_Arredondada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpanel_Borda_Arredondada1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelCelular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)))
                .addGroup(jpanel_Borda_Arredondada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanel_Borda_Arredondada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jFieldSobrenome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(64, 64, 64))
        );
        jpanel_Borda_Arredondada1Layout.setVerticalGroup(
            jpanel_Borda_Arredondada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_Borda_Arredondada1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jpanel_Borda_Arredondada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNome)
                    .addComponent(jFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanel_Borda_Arredondada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNome3)
                        .addComponent(jFieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpanel_Borda_Arredondada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpf1)
                    .addComponent(jFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail))
                .addGap(36, 36, 36)
                .addGroup(jpanel_Borda_Arredondada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFaixa)
                    .addGroup(jpanel_Borda_Arredondada1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxFaixas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCelular1)))
                .addGap(30, 30, 30)
                .addComponent(labelCelular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jpanel_Borda_Arredondada1);
        jpanel_Borda_Arredondada1.setBounds(80, 140, 580, 260);

        jpanel_Borda_Arredondada3.setLayout(null);

        labelAlunos.setFont(new java.awt.Font("Atletico Bold", 1, 24)); // NOI18N
        labelAlunos.setForeground(new java.awt.Color(251, 136, 52));
        labelAlunos.setText("Alunos");
        jpanel_Borda_Arredondada3.add(labelAlunos);
        labelAlunos.setBounds(474, 6, 130, 50);

        labelCadastro.setFont(new java.awt.Font("Atletico Bold", 1, 24)); // NOI18N
        labelCadastro.setForeground(new java.awt.Color(13, 32, 51));
        labelCadastro.setText("Cadastro:");
        jpanel_Borda_Arredondada3.add(labelCadastro);
        labelCadastro.setBounds(6, 6, 130, 50);

        jPanel1.add(jpanel_Borda_Arredondada3);
        jpanel_Borda_Arredondada3.setBounds(70, 30, 610, 50);

        botaoCadastro.setBackground(new java.awt.Color(251, 136, 52));
        botaoCadastro.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastroPNG.png"))); // NOI18N
        botaoCadastro.setBorder(new javax.swing.border.MatteBorder(null));
        botaoCadastro.setBorderPainted(false);
        botaoCadastro.setContentAreaFilled(false);
        botaoCadastro.setFocusPainted(false);
        botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(botaoCadastro);
        botaoCadastro.setBounds(330, 410, 90, 80);

        jMenu1.setText("Cadastrar");

        jMenuItem1.setText("Aluno");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Professor");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem4.setText("Matrícula");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Aluno");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Horarios");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Professor");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFieldNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFieldNomeKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c)||(c==KeyEvent.VK_SPACE) ||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_PERIOD)||(c==KeyEvent.VK_BACK_SPACE))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFieldNomeKeyTyped

    private void jFieldSobrenomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFieldSobrenomeKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c)||(c==KeyEvent.VK_SPACE) ||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_PERIOD)||(c==KeyEvent.VK_BACK_SPACE))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFieldSobrenomeKeyTyped

    private void jFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFieldEmailKeyTyped
        char c = evt.getKeyChar();
        if (Character.isWhitespace(c)) { // Verifica se o caractere é um espaço em branco
            evt.consume();
        }
    }//GEN-LAST:event_jFieldEmailKeyTyped

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroActionPerformed
        String nome = jFieldNome.getText();
        String cpf = jFieldCpf.getText();
        String sobrenome = jFieldSobrenome.getText();
        String email = jFieldEmail.getText();
        String celular = jFieldCelular.getText();
        Date dataNascimento = jDataNascimento.getDate();
        int idFaixa = -1;
        
        String corSelecionada = jComboBoxFaixas.getSelectedItem().toString();
        if(corSelecionada.equals("Selecione a Faixa")){
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma faixa válida.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        switch (corSelecionada) {
            case "Branca" -> idFaixa = 0;
            case "Amarela" -> idFaixa=1;
            case "Laranja" -> idFaixa=2;
            case "Verde" -> idFaixa=3;
            case "Azul" -> idFaixa=4;
            case "Roxa" -> idFaixa=5;
            case "Marrom" -> idFaixa=6;
            case "Preta" -> idFaixa=7;
            default -> {
                JOptionPane.showMessageDialog(this, "Faixa Inválida.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        if(idFaixa == -1){
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma faixa válida.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        if(nome.isEmpty()||cpf.isEmpty()||sobrenome.isEmpty()||email.isEmpty()||celular.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Certifique-se de Completar todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String query = "EXEC Karate.spInsereAluno ?,  ?,  ?,  ?,  ?,  ?,  ?";
            
            try {
                BDSQLServer.COMANDO.prepareStatement(query);
                BDSQLServer.COMANDO.setInt(1,idFaixa);                
                BDSQLServer.COMANDO.setString(2,nome);                
                BDSQLServer.COMANDO.setString(3,sobrenome);
                BDSQLServer.COMANDO.setString(4,cpf);
                BDSQLServer.COMANDO.setString(5,email);
                BDSQLServer.COMANDO.setString(6,celular);
                
                if (dataNascimento != null) 
                {
                    java.sql.Date sqldataNascimento = new java.sql.Date(dataNascimento.getTime());
                    BDSQLServer.COMANDO.setDate(7,sqldataNascimento);   
                    BDSQLServer.COMANDO.execute();
                    BDSQLServer.COMANDO.commit();
                    BDSQLServer.COMANDO.close();
                    JOptionPane.showMessageDialog(this, "Aluno Cadastrado..", "Alerta", JOptionPane.WARNING_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Por favor, selecione uma Data de Nascimento válida.", "Erro", JOptionPane.ERROR_MESSAGE);
  
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(jframeCadastroAlunos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
  
        
    }//GEN-LAST:event_botaoCadastroActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframeCadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframeCadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframeCadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframeCadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframeCadastroAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.demo.BirthdayEvaluator birthdayEvaluator1;
    private javax.swing.JButton botaoCadastro;
    private javax.swing.JComboBox<String> jComboBoxFaixas;
    private com.toedter.calendar.JDateChooser jDataNascimento;
    private javax.swing.JFormattedTextField jFieldCelular;
    private javax.swing.JFormattedTextField jFieldCpf;
    private javax.swing.JTextField jFieldEmail;
    private javax.swing.JFormattedTextField jFieldNome;
    private javax.swing.JFormattedTextField jFieldSobrenome;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private procedimentos.jpanel_Borda_Arredondada jpanel_Borda_Arredondada1;
    private procedimentos.jpanel_Borda_Arredondada jpanel_Borda_Arredondada3;
    private javax.swing.JLabel labelAlunos;
    private javax.swing.JLabel labelCadastro;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelCelular1;
    private javax.swing.JLabel labelCpf1;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFaixa;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNome3;
    // End of variables declaration//GEN-END:variables
}
