/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bushido_dojo.Deletes;

import bd.conexaoBD.BDSQLServer;
import bd.conexaoBD.core.MeuResultSet;
import com.mycompany.bushido_dojo.jframeHome;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dudac
 */
public class jframeDeleteMatricula extends javax.swing.JFrame {

    /**
     * Creates new form jframeDeleteMatricula
     */
    public jframeDeleteMatricula() {
        initComponents();
        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelBushido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        curvedGradientePanel1 = new procedimentos.CurvedGradientePanel();
        jLabel2 = new javax.swing.JLabel();
        jComboMatriculas = new javax.swing.JComboBox<>();
        labelHorarios1 = new javax.swing.JLabel();
        labelDataMatricula = new javax.swing.JLabel();
        labelHorarios2 = new javax.swing.JLabel();
        labelUltimoPagamento = new javax.swing.JLabel();
        labelVencimentoParcela = new javax.swing.JLabel();
        labelHorarios3 = new javax.swing.JLabel();
        labelMatriculaAtrasada = new javax.swing.JLabel();
        labelHorarios4 = new javax.swing.JLabel();
        labelHorarios5 = new javax.swing.JLabel();
        labelNomeCompleto = new javax.swing.JLabel();
        jbotaoSairHome = new javax.swing.JButton();
        labelNome2 = new javax.swing.JLabel();
        roundButton2 = new procedimentos.RoundButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(13, 32, 51));
        jPanel1.setLayout(null);

        jLabelBushido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N
        jPanel1.add(jLabelBushido);
        jLabelBushido.setBounds(10, 0, 50, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BushidoDojo DomineODomDaArte.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 10, 310, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 80);

        curvedGradientePanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Deletar Matricula");
        curvedGradientePanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 160, 30);

        jComboMatriculas.setBackground(new java.awt.Color(13, 32, 51));
        jComboMatriculas.setForeground(new java.awt.Color(255, 255, 255));
        jComboMatriculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Matrícula" }));
        jComboMatriculas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboMatriculasItemStateChanged(evt);
            }
        });
        curvedGradientePanel1.add(jComboMatriculas);
        jComboMatriculas.setBounds(30, 120, 180, 22);

        labelHorarios1.setFont(new java.awt.Font("Atletico Bold", 1, 24)); // NOI18N
        labelHorarios1.setForeground(new java.awt.Color(255, 255, 255));
        labelHorarios1.setText("Data Matricula:");
        curvedGradientePanel1.add(labelHorarios1);
        labelHorarios1.setBounds(40, 280, 200, 30);

        labelDataMatricula.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelDataMatricula.setForeground(new java.awt.Color(255, 255, 255));
        curvedGradientePanel1.add(labelDataMatricula);
        labelDataMatricula.setBounds(40, 320, 220, 30);

        labelHorarios2.setFont(new java.awt.Font("Atletico Bold", 1, 24)); // NOI18N
        labelHorarios2.setForeground(new java.awt.Color(255, 255, 255));
        labelHorarios2.setText("Vencimento da Parcela");
        curvedGradientePanel1.add(labelHorarios2);
        labelHorarios2.setBounds(470, 320, 300, 30);

        labelUltimoPagamento.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelUltimoPagamento.setForeground(new java.awt.Color(255, 255, 255));
        curvedGradientePanel1.add(labelUltimoPagamento);
        labelUltimoPagamento.setBounds(470, 230, 250, 30);

        labelVencimentoParcela.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelVencimentoParcela.setForeground(new java.awt.Color(255, 255, 255));
        curvedGradientePanel1.add(labelVencimentoParcela);
        labelVencimentoParcela.setBounds(490, 360, 250, 30);

        labelHorarios3.setFont(new java.awt.Font("Atletico Bold", 1, 24)); // NOI18N
        labelHorarios3.setForeground(new java.awt.Color(255, 255, 255));
        labelHorarios3.setText("Matricula Atrasada:");
        curvedGradientePanel1.add(labelHorarios3);
        labelHorarios3.setBounds(20, 380, 250, 30);

        labelMatriculaAtrasada.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelMatriculaAtrasada.setForeground(new java.awt.Color(255, 255, 255));
        curvedGradientePanel1.add(labelMatriculaAtrasada);
        labelMatriculaAtrasada.setBounds(280, 380, 100, 30);

        labelHorarios4.setFont(new java.awt.Font("Atletico Bold", 1, 24)); // NOI18N
        labelHorarios4.setForeground(new java.awt.Color(255, 255, 255));
        labelHorarios4.setText("Ultimo Pagamento");
        curvedGradientePanel1.add(labelHorarios4);
        labelHorarios4.setBounds(470, 190, 230, 30);

        labelHorarios5.setFont(new java.awt.Font("Atletico Bold", 1, 24)); // NOI18N
        labelHorarios5.setForeground(new java.awt.Color(255, 255, 255));
        labelHorarios5.setText("Nome");
        curvedGradientePanel1.add(labelHorarios5);
        labelHorarios5.setBounds(40, 200, 71, 30);

        labelNomeCompleto.setFont(new java.awt.Font("Atletico Bold", 1, 18)); // NOI18N
        labelNomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        curvedGradientePanel1.add(labelNomeCompleto);
        labelNomeCompleto.setBounds(30, 230, 300, 30);

        jbotaoSairHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/home.png"))); // NOI18N
        jbotaoSairHome.setBorderPainted(false);
        jbotaoSairHome.setContentAreaFilled(false);
        jbotaoSairHome.setFocusPainted(false);
        jbotaoSairHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotaoSairHomeActionPerformed(evt);
            }
        });
        curvedGradientePanel1.add(jbotaoSairHome);
        jbotaoSairHome.setBounds(710, 410, 80, 80);

        labelNome2.setFont(new java.awt.Font("The Bold Font", 1, 14)); // NOI18N
        labelNome2.setText("Home");
        curvedGradientePanel1.add(labelNome2);
        labelNome2.setBounds(730, 470, 90, 20);

        roundButton2.setBackground(new java.awt.Color(13, 32, 51));
        roundButton2.setText("Deletar");
        roundButton2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        roundButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton2ActionPerformed(evt);
            }
        });
        curvedGradientePanel1.add(roundButton2);
        roundButton2.setBounds(320, 440, 110, 40);

        getContentPane().add(curvedGradientePanel1);
        curvedGradientePanel1.setBounds(0, 80, 800, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboMatriculasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboMatriculasItemStateChanged
        displaySelectedMatricula();
    }//GEN-LAST:event_jComboMatriculasItemStateChanged

    private void jbotaoSairHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotaoSairHomeActionPerformed
        new jframeHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbotaoSairHomeActionPerformed

    private void roundButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton2ActionPerformed
        String selectedAluno = (String) jComboMatriculas.getSelectedItem();
        String[] partes = selectedAluno.split("\\s+");
        int idAluno = -1;
        String nomeCompleto = "";

        if(selectedAluno.equals("Selecione a Matrícula")){
            JOptionPane.showMessageDialog(this, "Selecione a Matricula que deseja deletar.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (partes.length >= 2) {
            idAluno = Integer.parseInt(partes[0]);

            for (int i = 1; i < partes.length; i++) {
                nomeCompleto += partes[i] + " ";
            }

            nomeCompleto = nomeCompleto.trim(); // Remove o espaço em branco extra do final, se houver
        } else {
            System.out.println("Formato inválido do item selecionado.");
        }

        String query = "DELETE Karate.Matricula WHERE Id_Aluno = ?";
        try {
            BDSQLServer.COMANDO.prepareStatement(query);
            BDSQLServer.COMANDO.setInt(1, idAluno);
            BDSQLServer.COMANDO.execute();
            BDSQLServer.COMANDO.commit();
            JOptionPane.showMessageDialog(this, "Aluno " + nomeCompleto +" foi deletado do banco de dados.");
            new jframeDeleteMatricula().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(jframeDeleteAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_roundButton2ActionPerformed

    private void fillComboBox() {
            try {
                String query = """
                               SELECT CONCAT(A.Id_Aluno, ' ', A.nome, ' ', A.sobrenome) AS NomeCompleto
                               FROM Karate.Aluno A
                               JOIN Karate.Matricula M ON A.Id_Aluno = M.Id_Aluno
                               
                               """;
                
                MeuResultSet resultado = (MeuResultSet)BDSQLServer.COMANDO.executeQuery (query);
                
                
                
                while (resultado.next()) {
                    jComboMatriculas.addItem(resultado.getString(1));
                }

                
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao preencher o ComboBox.");
            }
            
        }
    
    
    private void displaySelectedMatricula() {
        try {
            String selectedAluno = (String) jComboMatriculas.getSelectedItem();
            String[] partes = selectedAluno.split("\\s+");
            int idAluno = -1;
            if (partes.length >= 2) {
                 idAluno = Integer.parseInt(partes[0]);
            } else {
                System.out.println("Formato inválido do item selecionado.");
                return;
            }
            
            String query = "SELECT * from Karate.viewMatriculas where id_aluno = ?";
            BDSQLServer.COMANDO.prepareStatement(query);
            BDSQLServer.COMANDO.setInt(1, idAluno);
            MeuResultSet resultado = (MeuResultSet)BDSQLServer.COMANDO.executeQuery ();
            
            if(resultado.next()){
                Date dataMatriculasql = resultado.getDate(4);
                String nomeCompleto = resultado.getString(3);
                Date ultimoPgtosql = resultado.getDate(5);
                Date vencimentoParcelasql = resultado.getDate(6);
                String matriculaAtrasada = resultado.getString(7);
                
                String vencimentoParcela =new SimpleDateFormat("dd/MM/yyyy").format(vencimentoParcelasql);
                String ultimoPgto =new SimpleDateFormat("dd/MM/yyyy").format(ultimoPgtosql);
                String dataMatricula = new SimpleDateFormat("dd/MM/yyyy").format(dataMatriculasql);
                
                labelNomeCompleto.setText(nomeCompleto);
                labelUltimoPagamento.setText(ultimoPgto);
                labelDataMatricula.setText(dataMatricula);
                labelVencimentoParcela.setText(vencimentoParcela);
                labelMatriculaAtrasada.setText(matriculaAtrasada);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao exibir informações do aluno.");
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframeDeleteMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframeDeleteMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframeDeleteMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframeDeleteMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframeDeleteMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private procedimentos.CurvedGradientePanel curvedGradientePanel1;
    private javax.swing.JComboBox<String> jComboMatriculas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBushido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbotaoSairHome;
    private javax.swing.JLabel labelDataMatricula;
    private javax.swing.JLabel labelHorarios1;
    private javax.swing.JLabel labelHorarios2;
    private javax.swing.JLabel labelHorarios3;
    private javax.swing.JLabel labelHorarios4;
    private javax.swing.JLabel labelHorarios5;
    private javax.swing.JLabel labelMatriculaAtrasada;
    private javax.swing.JLabel labelNome2;
    private javax.swing.JLabel labelNomeCompleto;
    private javax.swing.JLabel labelUltimoPagamento;
    private javax.swing.JLabel labelVencimentoParcela;
    private procedimentos.RoundButton roundButton2;
    // End of variables declaration//GEN-END:variables
}
