/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bushido_dojo;
import bd.conexaoBD.*;
import bd.conexaoBD.core.*;
import bdfuncionalidades.*;
import com.mycompany.bushido_dojo.Cadastros.jframeCadastroAlunos;
import com.mycompany.bushido_dojo.jframeBushido_Dojo.*;
import javax.swing.JLabel;
/**
 *
 * @author dudac
 */
public class jframeHome extends javax.swing.JFrame {

    /**
     * Creates new form jframeHome
     */
    
    public jframeHome() {
        initComponents();
        PreencheTabelas preencheTabelas = new PreencheTabelas();
        preencheTabelas.preencherTabela(jtableHorarios, "SELECT * FROM Karate.viewHorariosJava");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelMiyagi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableHorarios = new javax.swing.JTable();
        labelHorarios = new javax.swing.JLabel();
        labelMiyagi2 = new javax.swing.JLabel();
        jpanel_Borda_Arredondada1 = new procedimentos.jpanel_Borda_Arredondada();
        botaoSair2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(13, 32, 51));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Atletico Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 136, 52));
        jLabel2.setText("Bem Vindo!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 40, 140, 30);

        labelMiyagi.setFont(new java.awt.Font("Atletico Bold", 0, 14)); // NOI18N
        labelMiyagi.setForeground(new java.awt.Color(255, 255, 255));
        labelMiyagi.setText("Senhor Miyagi, interpretado por Pat Morita - \"Karate Kid\" (1984).");
        jPanel1.add(labelMiyagi);
        labelMiyagi.setBounds(290, 390, 490, 30);

        jtableHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtableHorarios);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(110, 160, 520, 90);

        labelHorarios.setFont(new java.awt.Font("Atletico Bold", 1, 24)); // NOI18N
        labelHorarios.setForeground(new java.awt.Color(251, 136, 52));
        labelHorarios.setText("Horarios da Semana");
        jPanel1.add(labelHorarios);
        labelHorarios.setBounds(110, 120, 260, 50);

        labelMiyagi2.setFont(new java.awt.Font("Atletico Bold", 1, 24)); // NOI18N
        labelMiyagi2.setForeground(new java.awt.Color(255, 255, 255));
        labelMiyagi2.setText("\"Manter a mente quieta, a espinha ereta e o coração tranquilo.\"");
        jPanel1.add(labelMiyagi2);
        labelMiyagi2.setBounds(10, 340, 790, 50);

        jpanel_Borda_Arredondada1.setLayout(null);

        botaoSair2.setBackground(new java.awt.Color(13, 32, 51));
        botaoSair2.setForeground(new java.awt.Color(255, 255, 255));
        botaoSair2.setText("Sair");
        botaoSair2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.lightGray));
        botaoSair2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSair2MouseClicked(evt);
            }
        });
        jpanel_Borda_Arredondada1.add(botaoSair2);
        botaoSair2.setBounds(250, 20, 250, 30);

        jPanel1.add(jpanel_Borda_Arredondada1);
        jpanel_Borda_Arredondada1.setBounds(0, 470, 800, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 570);

        jMenu1.setText("Cadastrar");

        jMenuItem1.setText("Aluno");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Professor");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem4.setText("Matrícula");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Aluno");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Horarios");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Professor");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new jframeCadastroAlunos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void botaoSair2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSair2MouseClicked
        this.dispose();
    }//GEN-LAST:event_botaoSair2MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                jframeHome jframeHomeWindow = new jframeHome();
                jframeHomeWindow.setVisible(true);

            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSair2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private procedimentos.jpanel_Borda_Arredondada jpanel_Borda_Arredondada1;
    private javax.swing.JTable jtableHorarios;
    private javax.swing.JLabel labelHorarios;
    private javax.swing.JLabel labelMiyagi;
    private javax.swing.JLabel labelMiyagi2;
    // End of variables declaration//GEN-END:variables
}
