package com.mycompany.bushido_dojo;

import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dudac
 */
public class jframeBushido_Dojo extends javax.swing.JFrame {

    /**
     * Creates new form jframeBushido_Dojo
     */
    public jframeBushido_Dojo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelBushidoFooter = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botaoSair = new javax.swing.JButton();
        botaoEntrar = new javax.swing.JButton();
        labelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        senhaLabel = new javax.swing.JLabel();
        senhaField = new javax.swing.JPasswordField();
        idUsuarioLabel = new javax.swing.JLabel();
        idUsuarioField = new javax.swing.JFormattedTextField();
        cpfLabel = new javax.swing.JLabel();
        cpfField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bushido Dojo");
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(13, 32, 51));
        jPanel1.setLayout(null);

        labelBushidoFooter.setFont(new java.awt.Font("Rodchenko Grotesk ML", 1, 24)); // NOI18N
        labelBushidoFooter.setForeground(new java.awt.Color(204, 204, 204));
        labelBushidoFooter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBushidoFooter.setText("Bushido Dojo");
        jPanel1.add(labelBushidoFooter);
        labelBushidoFooter.setBounds(562, 473, 138, 27);

        jPanel2.setBackground(new java.awt.Color(100, 100, 100));
        jPanel2.setLayout(null);

        botaoSair.setBackground(new java.awt.Color(13, 32, 51));
        botaoSair.setForeground(new java.awt.Color(255, 255, 255));
        botaoSair.setText("Sair");
        botaoSair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.lightGray));
        jPanel2.add(botaoSair);
        botaoSair.setBounds(190, 380, 102, 36);

        botaoEntrar.setBackground(new java.awt.Color(13, 32, 51));
        botaoEntrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoEntrar.setText("Entrar");
        botaoEntrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.lightGray));
        jPanel2.add(botaoEntrar);
        botaoEntrar.setBounds(40, 380, 102, 36);

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N
        jPanel2.add(labelLogo);
        labelLogo.setBounds(130, 20, 50, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BushidoDojo DomineODomDaArte.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 80, 320, 40);

        jPanel5.setLayout(null);

        senhaLabel.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        senhaLabel.setText("Senha:");
        jPanel5.add(senhaLabel);
        senhaLabel.setBounds(70, 110, 48, 16);
        jPanel5.add(senhaField);
        senhaField.setBounds(120, 110, 100, 20);

        idUsuarioLabel.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        idUsuarioLabel.setText("Usuário:");
        jPanel5.add(idUsuarioLabel);
        idUsuarioLabel.setBounds(60, 60, 60, 16);

        idUsuarioField.setForeground(new java.awt.Color(153, 153, 153));
        idUsuarioField.setText("Digite o Usuário");
        idUsuarioField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idUsuarioFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idUsuarioFieldFocusLost(evt);
            }
        });
        jPanel5.add(idUsuarioField);
        idUsuarioField.setBounds(120, 60, 100, 22);

        cpfLabel.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        cpfLabel.setText("CPF:");
        jPanel5.add(cpfLabel);
        cpfLabel.setBounds(80, 30, 41, 16);

        try {
            cpfField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(cpfField);
        cpfField.setBounds(120, 28, 100, 22);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 150, 310, 180);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 0, 310, 500);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idUsuarioFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idUsuarioFieldFocusGained
        if(idUsuarioField.getText().equals("Digite o Usuário"))
        {
            idUsuarioField.setText("");
            idUsuarioField.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_idUsuarioFieldFocusGained

    private void idUsuarioFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idUsuarioFieldFocusLost
        if(idUsuarioField.getText().equals(""))
        {
            idUsuarioField.setText("Digite o Usuário");
            idUsuarioField.setForeground(new Color(0,0,0));
            
        }
    }//GEN-LAST:event_idUsuarioFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframeBushido_Dojo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframeBushido_Dojo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframeBushido_Dojo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframeBushido_Dojo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframeBushido_Dojo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JFormattedTextField cpfField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JFormattedTextField idUsuarioField;
    private javax.swing.JLabel idUsuarioLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelBushidoFooter;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JPasswordField senhaField;
    private javax.swing.JLabel senhaLabel;
    // End of variables declaration//GEN-END:variables
}
