/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bushido_dojo;
import bd.conexaoBD.*;
import bd.conexaoBD.core.*;
import com.mycompany.bushido_dojo.jframeBushido_Dojo.*;
import javax.swing.JLabel;
/**
 *
 * @author dudac
 */
public class jframeHome extends javax.swing.JFrame {

    /**
     * Creates new form jframeHome
     */
    private static String username;

    public void setUsername(String username) {
        this.username = username;
    }
    public jframeHome(String username) {
        initComponents();
        atualizaLabel (labelUsername, username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHorarios = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(13, 32, 51));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Atletico Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 136, 52));
        jLabel2.setText("Bem Vindo!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 70, 140, 30);

        labelUsername.setFont(new java.awt.Font("Atletico Bold", 1, 24)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(labelUsername);
        labelUsername.setBounds(240, 70, 450, 30);

        jScrollPane1.setBackground(new java.awt.Color(242, 242, 242));

        jTableHorarios.setBackground(new java.awt.Color(197, 197, 197));
        jTableHorarios.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.darkGray));
        jTableHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableHorarios.setGridColor(new java.awt.Color(255, 102, 0));
        jScrollPane1.setViewportView(jTableHorarios);
        if (jTableHorarios.getColumnModel().getColumnCount() > 0) {
            jTableHorarios.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            jTableHorarios.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            jTableHorarios.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            jTableHorarios.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 250, 590, 240);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 570);

        jMenu1.setText("Cadastrar");

        jMenuItem1.setText("Aluno");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Professor");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem4.setText("Matrícula");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Aluno");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Horarios");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Professor");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void atualizaLabel(JLabel label, String texto) {
        label.setText(texto);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                jframeHome jframeHomeWindow = new jframeHome(username);
                jframeHomeWindow.setVisible(true);

            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHorarios;
    private javax.swing.JLabel labelUsername;
    // End of variables declaration//GEN-END:variables
}
